version: '3'
services:
  gourd-hu:
    image: tomcat:8
    ports:
      - "8086:8080"
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx300m -Xms300m -Xmn200m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    volumes:
      - "./volumes/tomcat-web/webapps:/usr/local/tomcat/webapps"
      - "./volumes/tomcat-web/logs:/usr/local/tomcat/logs"
    container_name: admin-web
    mem_limit: 512m
